language: node_js
node_js:
    - 'lts/*'
cache: npm
install:
    - npm ci
    - npm link
    - cd example
    - npm ci
    - npm link ts-audit
    - cd ..
script:
    - npm run build
    - npm run lint
    - npm test
    - cd example
    - npm run build
