// prettier-ignore-start
// tslint:disable
/*
 * This file was automatically generated by something else. Probably shouldn't touch it.
 */
import * as _unused from "./src/lib";
import { ExternalInterface } from "./example/interfaces";
import { CustomName } from "./example/interfaces";
import { References } from "./example/interfaces";

declare namespace Validate {
  function validate(
    interfaceName: "ExternalInterface",
    obj: any
  ): ExternalInterface;
  function validate(interfaceName: "CustomName", obj: any): CustomName;
  function validate(interfaceName: "References", obj: any): References;
  function validate(interfaceName: string, obj: any): never;
}

declare module "./src/lib" {
  // @ts-ignore
  export function validator(schemaPath: string): typeof Validate.validate;
}
